#!/bin/bash
################################################################################
# host prep
################################################################################
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 07B8937284F281ED
sudo add-apt-repository ppa:ubuntu-389-directory-server/ppa
apt-get update
apt-get install -y 389-admin 389-ds-base 389-ds-console 389-console 389-admin-console ldap-utils

grep "echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time" /etc/rc.local || echo "echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time" >> /etc/rc.local
sed -ie 's/^exit 0/#exit 0/' /etc/rc.local
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time

cp /etc/pam.d/su /etc/pam.d/su.dist
sed -ie 's/# session    required   pam_limits.so/session    required   pam_limits.so/' /etc/pam.d/su

cp /etc/security/limits.conf /etc/security/limits.conf.dist
cat<<EOF | while read line; do grep "$line" /etc/security/limits.conf || echo "$line" >> /etc/security/limits.conf ; done
root          soft    nofile           4096
root          hard    nofile           40960
dirsrv        soft    nofile           4096
dirsrv        hard    nofile           40960
EOF

cp /etc/sysctl.conf /etc/sysctl.conf.dist
grep "fs.file-max = 100000" /etc/sysctl.conf || echo "fs.file-max = 100000" >> /etc/sysctl.conf && sysctl -p

# 389-ds requires the forward lookup to match the reverse lookup or it will complain and/or not start
IP_ETH0=$(ifconfig eth0 | grep 'inet addr:' | sed -e 's/.*inet addr://g' -e 's/ .*//')
grep "$IP_ETH0 *$(hostname)" /etc/hosts||echo "$IP_ETH0 $(hostname -f) $(hostname -s)" >> /etc/hosts

################################################################################
# Reboot, add ram, disk (if necessary)
################################################################################
cat<<EOF > /root/setup-ds.inf
[General]
FullMachineName= $(hostname -f)
SuiteSpotUserID= dirsrv
SuiteSpotGroup= dirsrv
ConfigDirectoryLdapURL= ldap://$(hostname -f):389/o=NetscapeRoot
ConfigDirectoryAdminID= admin
ConfigDirectoryAdminPwd= bobloblaw
AdminDomain= $(hostname -d)

[slapd]
ServerIdentifier= $(hostname -s)
ServerPort= 389
Suffix= dc=$(echo $(hostname -d)|sed -e 's/\./,dc=/g')
RootDN= cn=Directory Manager
RootDNPwd= bobloblaw

[admin]
ServerAdminID= admin
ServerAdminPwd= bobloblaw
SysUser= dirsrv
EOF

/usr/sbin/setup-ds-admin -s -f /root/setup-ds.inf
ldapsearch -xLLLHldap://$(hostname -f):389 -b"dc=$(hostname -d|sed -e's/\./,dc=/g')" -D "cn=Directory Manager" -w "bobloblaw"
EXIT=$?;
if [ $EXIT -eq 0 ];then /bin/rm /root/setup-ds.inf ; fi 
exit $EXIT;

# /usr/sbin/remove-ds-admin.pl -y
# /usr/sbin/setup-ds-admin.pl -s -f /etc/dirsrv/config/setup-ds-admin.inf
/usr/sbin/setup-ds-admin

# admin                J4stg,l14lw.
# cn=Directory Manager J4cb,b4r1sD.
# register with ldap://faraday.eftdomain.net:389/o=NetscapeRoot

################################################################################
# add certs
################################################################################
# scp faraday:{maxwell-backup.p12,midca.pem,rootca.pem} .
# scp faraday.eftdomain.net:{midca.pem,rootca.pem} .
certutil -d /etc/dirsrv/slapd-$(hostname -s) -L

certutil -A -d /etc/dirsrv/slapd-$(hostname -s) -n "eftdomain.net intermediate ca" -t "CT,," -a -i midca.pem
certutil -A -d /etc/dirsrv/slapd-$(hostname -s) -n "eftdomain.net root ca" -t "CT,," -a -i rootca.pem
pk12util -i $(hostname -s)-backup.p12 -d /etc/dirsrv/slapd-$(hostname -s) # J4stg,l14lw.  (import)
# pk12util -d . -o $(hostname -s)-backup.p12 -n "$(hostname -s).eftdomain.net-cert" # (export)

certutil -d /etc/dirsrv/admin-serv -L
certutil -A -d /etc/dirsrv/admin-serv -n "eftdomain.net intermediate ca" -t "CT,," -a -i midca.pem
certutil -A -d /etc/dirsrv/admin-serv -n "eftdomain.net root ca" -t "CT,," -a -i rootca.pem
pk12util -i $(hostname -s)-backup.p12 -h "$(hostname -f)-cert" -d /etc/dirsrv/admin-serv -W "$(secret)" # J4stg,l14lw. (import)

echo "Internal (Software) Token:J4stg,l14lw." > /etc/dirsrv/slapd-$(hostname -s)/pin.txt
echo "internal:J4stg,l14lw." > /etc/dirsrv/admin-serv/password.conf

################################################################################
# Enable SSL
################################################################################
cat<<EOF > /tmp/ssl_enable.ldif
dn: cn=encryption,cn=config
changetype: modify
replace: nsSSL3
nsSSL3: on
-
replace: nsSSLClientAuth
nsSSLClientAuth: allowed
-
add: nsSSL3Ciphers
nsSSL3Ciphers: -rsa_null_md5,+rsa_rc4_128_md5,+rsa_rc4_40_md5,+rsa_rc2_40_md5,+rsa_des_sha,+rsa_fips_des_sha,+rsa_3des_sha,+rsa_fips_3des_sha,+fortezza,+fortezza_rc4_128_sha,+fortezza_null,+tls_rsa_export1024_with_rc4_56_sha,+tls_rsa_export1024_with_des_cbc_sha,-rc4,-rc4export,-rc2,-rc2export,-des,-desede3

dn: cn=config
changetype: modify
add: nsslapd-security
nsslapd-security: on
-
replace: nsslapd-ssl-check-hostname
nsslapd-ssl-check-hostname: off
EOF

ldapmodify -xH ldap://127.0.0.1:389 -D "cn=Directory manager" -w J4cb,b4r1sD. -f /tmp/ssl_enable.ldif

cat<<EOF > /tmp/addRSA.ldif
dn: cn=RSA,cn=encryption,cn=config
changetype: add
objectclass: top
objectclass: nsEncryptionModule
cn: RSA
nsSSLPersonalitySSL: $(hostname -f)-cert
nsSSLToken: internal (software)
nsSSLActivation: on
EOF
ldapmodify -xH ldap://127.0.0.1:389 -D "cn=Directory manager" -w J4cb,b4r1sD. -f /tmp/addRSA.ldif

################################################################################
#!!! copy any extra schema files to /etc/dirsrv/slapd-$(hostname -s)/schema !!!
################################################################################
(cd /etc/dirsrv/slapd-$(hostname -s)/schema/; cp 99user.ldif 99user.ldif.dist)
(cd /etc/dirsrv/slapd-$(hostname -s)/schema/; scp root@faraday.eftdomain.net:/etc/dirsrv/slapd-faraday/schema/{70samba.ldif,75dhcp.ldif,99user.ldif} .)
/etc/init.d/dirsrv restart

################################################################################
# Enable replication
################################################################################

cat<<EOF > /tmp/repl.ldif
# replication manager, config
dn: cn=replication manager,cn=config
objectClass: top
objectClass: person
cn: Replication Manager
sn: Manager
userPassword:: e1NTSEF9QzR0SDl0cGdkSm5VY3lJQXMrS3VYY0lEVWlOVVpHdHM=
EOF
ldapadd -xH ldap://127.0.0.1:389 -D "cn=Directory manager" -w J4cb,b4r1sD. -f /tmp/repl.ldif

################################################################################
# Enable SSL on the admin-serv
################################################################################
http://directory.fedoraproject.org/wiki/Howto:SSL#Admin_Server_SSL_Information

