#!/bin/bash
(cd ~/boxes/boron ; cat ~/.ssh/id_rsa.pub | vagrant ssh -- "cat - >> ~/.ssh/authorized_keys" )
cat ~/Documents/boron/389-ds-ubuntu | ( cd ~/boxes/boron ; vagrant ssh -- "sudo tee 389-ds-ubuntu" )

cat<<EOF |( cd ~/boxes/boron ; vagrant ssh )
echo "boron.jameswhite.org" | sudo tee /etc/hostname
sudo hostname boron.jameswhite.org
sudo bash 389-ds-ubuntu
EOF

# for pkg in $(dpkg -l | grep 389 | awk '{print $2}' | grep "^389"); do dpkg -L $pkg | sed -e "s/^/$pkg: /"; done | grep admin.inf
